// 安全桥接: 暴露受控 API 给渲染进程
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  ocrInfo: () => ipcRenderer.invoke('ocr:info'),
  srvProbe: (url) => ipcRenderer.invoke('srv:probe', url),
  saveConfig: (cfg) => ipcRenderer.invoke('config:save', cfg),
  testConnect: () => ipcRenderer.invoke('connect:test'),
  serverTest: (baseUrl, token) => ipcRenderer.invoke('server:test', baseUrl, token),
  listMRs: () => ipcRenderer.invoke('mrs:list'),
  listHistoryMRs: () => ipcRenderer.invoke('mrs:history'),
  reviewHistory: () => ipcRenderer.invoke('reviews:list'),
  runReview: (iid) => ipcRenderer.invoke('review:run', iid),
  stopReview: () => ipcRenderer.invoke('review:stop'),
  postComments: (iid, comments, expectRepoKey, historyReview) => ipcRenderer.invoke('review:post', iid, comments, expectRepoKey, historyReview),
  commitPost: (sha, comments, historyReview) => ipcRenderer.invoke('commit:post', sha, comments, historyReview),
  fixCommit: (sha, selIdx) => ipcRenderer.invoke('fix:commit', sha, selIdx),
  openUrl: (url) => ipcRenderer.invoke('open:url', url),
  openCommit: (sha) => ipcRenderer.invoke('open:commit', sha),
  copyText: (text) => ipcRenderer.invoke('clip:write', text),
  zoom: (dir) => ipcRenderer.invoke('ui:zoom', dir),
  // M2: 卡控 + 队列
  gateStatus: () => ipcRenderer.invoke('gate:status'),
  gateRecheck: () => ipcRenderer.invoke('gate:recheck'),
  adminAuth: (password) => ipcRenderer.invoke('admin:auth', password),
  adminRevoke: () => ipcRenderer.invoke('admin:revoke'),
  llmModels: (baseUrl, apiKey) => ipcRenderer.invoke('llm:models', baseUrl, apiKey),
  validateLlm: (baseUrl, apiKey, model) => ipcRenderer.invoke('llm:validate', baseUrl, apiKey, model),
  flushQueue: () => ipcRenderer.invoke('queue:flush'),
  // M3: 提交树
  listBranches: () => ipcRenderer.invoke('commits:branches'),
  listCommits: (branch, all) => ipcRenderer.invoke('commits:list', branch, all),
  runCommitReview: (sha) => ipcRenderer.invoke('commit:review', sha),
  // M4: 自动修复
  runAutoFix: (iid, selIdx) => ipcRenderer.invoke('fix:run', iid, selIdx),
  fixStatus: () => ipcRenderer.invoke('fix:status'),
  onLog: (cb) => ipcRenderer.on('log', (_e, line) => cb(line)),
  onRepoSwitched: (cb) => ipcRenderer.on('repo:switched', (_e, idx) => cb(idx)),
  scheduleList: () => ipcRenderer.invoke('schedule:list'),
  scheduleCreate: (t) => ipcRenderer.invoke('schedule:create', t),
  scheduleUpdate: (id, patch) => ipcRenderer.invoke('schedule:update', id, patch),
  scheduleDelete: (id) => ipcRenderer.invoke('schedule:delete', id),
  onMrsRefresh: (cb) => ipcRenderer.on('mrs:refresh', (_e, repoIdx) => cb(repoIdx)),
  onSchedTick: (cb) => ipcRenderer.on('schedule:tick', (_e, info) => cb(info)),
});